# Desafios - Módulo 3 - Resueltos

In [ ]:
import numpy as np

- Ejercicio 1

    - A- Construir arrays a partir de una lista simple y una lista anidada usando tipos de datos numéricos distintos para cada una.
    -B- Construir un array lineal de 36 elementos. Cambiar el shape para que tenga:
        - 3 filas y 12 columnas 
        - 4 columnas 

    
Parte A:

In [5]:
simple = [10,20.5,30]
matriz = [[11.1,20],[50.5,70]]

asimple = np.array(simple)
amatriz = np.array(matriz)

In [6]:
asimple

array([10. , 20.5, 30. ])

In [7]:
amatriz

array([[11.1, 20. ],
       [50.5, 70. ]])

Parte B:

In [9]:
vector = np.arange(36)

In [10]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [11]:
vector.reshape(3,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

- Ejercicio 2 
    - Dado un vector de pesos(kg) y otro vector alturas(metros), calcular el índice de masa corporal general (un vector imc).


In [2]:
pesos = np.array([50,65.5,89.2,100])
alturas = np.array([1.6,1.7,1.8,1.75])

In [4]:
imc = pesos / (alturas**2)
imc

array([19.53125   , 22.66435986, 27.5308642 , 32.65306122])

- Ejercicio 3
    - Crear un vector con diez números, todos ceros
    - Crear un vector con diez números al azar
    - Crear una matriz de 2x3 y multiplicarla por su transpuesta

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.random.random((10,))

array([0.58155521, 0.65300166, 0.13684951, 0.53893691, 0.37449019,
       0.25087429, 0.73133042, 0.78648521, 0.37213616, 0.61196859])

In [37]:
m = np.array([[0, 1],[2, 3]])
m * np.transpose(m)

array([[0, 2],
       [2, 9]])